version: '3.9'

services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - ./mongodb:/data/db

  mongo-seed:
    container_name: mongo_seed
    build: ./mongo-seed
    links:
      - mongodb
