version: "2" # The Docker version

volumes:
    mongo_volume:

services:
    app:
        build: .
        depends_on:
            - mongodb
        environment:
            - MONGO_LOCAL_URL=mongodb
            - DEV_MODE=true
        ports:
            - 3000:3000
    mongodb:
        image: mongo:latest
        restart: unless-stopped
        ports:
            - '27017:27017'
        volumes:
            - ./mongodb:/data/db