version: "2" # The Docker version

volumes:
    mongo_volume:

services:
    mongodb:
        image: mongo:latest
        restart: unless-stopped
        ports:
            - '27017:27017'
        volumes:
            - ./mongodb:/data/db