// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Activate: typeof import('./src/components/Auth/Activate.vue')['default']
    AlternativeTaskList: typeof import('./src/components/Tasks/AlternativeTaskList.vue')['default']
    AlternativeTaskListItem: typeof import('./src/components/Tasks/Tasks-Components/AlternativeTaskListItem.vue')['default']
    AppButton: typeof import('./src/components/shared/Input/AppButton.vue')['default']
    AppChip: typeof import('./src/components/shared/UI/AppChip.vue')['default']
    AppCollapsible: typeof import('./src/components/shared/UI/AppCollapsible.vue')['default']
    AppDropDownMenu: typeof import('./src/components/shared/Input/AppDropDownMenu.vue')['default']
    AppFloatingActionButton: typeof import('./src/components/shared/UI/AppFloatingActionButton.vue')['default']
    AppForm: typeof import('./src/components/shared/Input/AppForm.vue')['default']
    AppIcon: typeof import('./src/components/shared/UI/AppIcon.vue')['default']
    AppInlineInputField: typeof import('./src/components/shared/Input/AppInlineInputField.vue')['default']
    AppInputField: typeof import('./src/components/shared/Input/AppInputField.vue')['default']
    AppLabel: typeof import('./src/components/shared/Input/AppLabel.vue')['default']
    AppModal: typeof import('./src/components/shared/Modal/AppModal.vue')['default']
    AppProgressBar: typeof import('./src/components/shared/UI/AppProgressBar.vue')['default']
    AppToolTip: typeof import('./src/components/shared/UI/AppToolTip.vue')['default']
    AppYesNoModal: typeof import('./src/components/shared/Modal/AppYesNoModal.vue')['default']
    CreateLevelForm: typeof import('./src/components/Levels/CreateLevelForm.vue')['default']
    Dashboard: typeof import('./src/components/Dashboard/Dashboard.vue')['default']
    DraggableItem: typeof import('./src/components/shared/DragAndDrop/DraggableItem.vue')['default']
    DropZone: typeof import('./src/components/shared/DragAndDrop/DropZone.vue')['default']
    EpicCard: typeof import('./src/components/Epics/EpicCard.vue')['default']
    EpicDetails: typeof import('./src/components/Epics/EpicDetails.vue')['default']
    ForgotPassword: typeof import('./src/components/Auth/ForgotPassword.vue')['default']
    InitiativeCard: typeof import('./src/components/Initiatives/Initiatives-Components/InitiativeCard.vue')['default']
    InitiativeDetails: typeof import('./src/components/Initiatives/InitiativeDetails.vue')['default']
    Initiatives: typeof import('./src/components/Initiatives/Initiatives.vue')['default']
    Levels: typeof import('./src/components/Levels/Levels.vue')['default']
    Login: typeof import('./src/components/Auth/Login.vue')['default']
    ObjectiveCard: typeof import('./src/components/Objectives/Objectives-Components/ObjectiveCard.vue')['default']
    ObjectiveDetails: typeof import('./src/components/Objectives/ObjectiveDetails.vue')['default']
    Objectives: typeof import('./src/components/Objectives/Objectives.vue')['default']
    Profile: typeof import('./src/components/Profile/Profile.vue')['default']
    ProjectCard: typeof import('./src/components/Projects/Projects-Components/ProjectCard.vue')['default']
    ProjectDashboard: typeof import('./src/components/Projects/ProjectDashboard.vue')['default']
    ProjectEpics: typeof import('./src/components/Projects/ProjectEpics.vue')['default']
    ProjectLayout: typeof import('./src/components/Projects/ProjectLayout.vue')['default']
    Projects: typeof import('./src/components/Projects/Projects.vue')['default']
    ProjectSettings: typeof import('./src/components/Projects/ProjectSettings.vue')['default']
    Register: typeof import('./src/components/Auth/Register.vue')['default']
    ResetPassword: typeof import('./src/components/Auth/ResetPassword.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterNesting: typeof import('./src/components/shared/RouterNesting.vue')['default']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./src/components/Settings/Settings.vue')['default']
    TaskList: typeof import('./src/components/Tasks/TaskList.vue')['default']
    TaskListItem: typeof import('./src/components/Tasks/Tasks-Components/TaskListItem.vue')['default']
    Test: typeof import('./src/components/shared/Test.vue')['default']
  }
}
