// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Activate: typeof import('./src/views/Auth/Activate.vue')['default']
    AppButton: typeof import('./src/components/shared/Input/AppButton.vue')['default']
    AppChip: typeof import('./src/components/shared/UI/AppChip.vue')['default']
    AppCollapsible: typeof import('./src/components/shared/UI/AppCollapsible.vue')['default']
    AppDropDownMenu: typeof import('./src/components/shared/Input/AppDropDownMenu.vue')['default']
    AppFloatingActionButton: typeof import('./src/components/shared/UI/AppFloatingActionButton.vue')['default']
    AppForm: typeof import('./src/components/shared/Input/AppForm.vue')['default']
    AppIcon: typeof import('./src/components/shared/UI/AppIcon.vue')['default']
    AppInlineInputField: typeof import('./src/components/shared/Input/AppInlineInputField.vue')['default']
    AppInputField: typeof import('./src/components/shared/Input/AppInputField.vue')['default']
    AppLabel: typeof import('./src/components/shared/Input/AppLabel.vue')['default']
    AppModal: typeof import('./src/components/shared/Modal/AppModal.vue')['default']
    AppProgressBar: typeof import('./src/components/shared/UI/AppProgressBar.vue')['default']
    AppToolTip: typeof import('./src/components/shared/UI/AppToolTip.vue')['default']
    AppYesNoModal: typeof import('./src/components/shared/Modal/AppYesNoModal.vue')['default']
    Auth: typeof import('./src/layouts/Auth.vue')['default']
    CreateGroupFormModal: typeof import('./src/components/Groups/CreateGroupFormModal.vue')['default']
    CreateLevelFormModal: typeof import('./src/components/Levels/CreateLevelFormModal.vue')['default']
    CreateOrganizationFormModal: typeof import('./src/components/Organizations/CreateOrganizationFormModal.vue')['default']
    Dashboard: typeof import('./src/components/Dashboard/Dashboard.vue')['default']
    DraggableItem: typeof import('./src/components/shared/DragAndDrop/DraggableItem.vue')['default']
    DropZone: typeof import('./src/components/shared/DragAndDrop/DropZone.vue')['default']
    ForgotPassword: typeof import('./src/views/Auth/ForgotPassword.vue')['default']
    GroupCard: typeof import('./src/components/Groups/GroupCard.vue')['default']
    GroupView: typeof import('./src/views/GroupView.vue')['default']
    LevelList: typeof import('./src/components/Levels/LevelList.vue')['default']
    Levels: typeof import('./src/views/Levels.vue')['default']
    LevelView: typeof import('./src/views/LevelView.vue')['default']
    Login: typeof import('./src/views/Auth/Login.vue')['default']
    Main: typeof import('./src/layouts/Main.vue')['default']
    NotFound: typeof import('./src/views/NotFound.vue')['default']
    OrganizationView: typeof import('./src/views/OrganizationView.vue')['default']
    Profile: typeof import('./src/components/Profile/Profile.vue')['default']
    Register: typeof import('./src/views/Auth/Register.vue')['default']
    ResetPassword: typeof import('./src/views/Auth/ResetPassword.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterNesting: typeof import('./src/components/shared/RouterNesting.vue')['default']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./src/components/Settings/Settings.vue')['default']
  }
}
