name: Docker Image CI/CD Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted 
    environment: 
      name: production
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        cd prototype
        docker build . --file "Dockerfile" --tag bachelor:latest
    
  deploy:
    runs-on: self-hosted
    # environment: 
    #   name: production
    steps:
      - name: Deploy the newest Docker image
        run: docker compose -f "prototype/docker-compose.ci.yml" up -d