name: Docker Image CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted 
    steps:
    - name: Build the Docker image
      run: |
        cd prototype
        docker build . --file "prototype/Dockerfile" --tag bachelor:latest
    
  deploy:
    runs-on: self-hosted 
    steps:
      - name: Deploy the newest Docker image
        run: docker compose -f "prototype/docker-compose.yml" up -d