name: Docker Image CI/CD Pipeline

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted 
    environment: 
      name: production
    env:
      MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
      SECRET: ${{ secrets.SECRET }}
      CLIENT_APP_URL: ${{ vars.CLIENT_APP_URL }}
      MONGO_DB: ${{ vars.MONGO_DB }}
      MONGO_URL: ${{ vars.MONGO_URL }}
      MONGO_USER: ${{ vars.MONGO_USER }}
      SMTP_HOST: ${{ vars.SMTP_HOST }}
      SMTP_PORT: ${{ vars.SMTP_PORT }}
      SMTP_USER: ${{ vars.SMTP_USER }}
      VITE_API_URL: ${{ vars.VITE_API_URL }}
      VITE_APP_DEV_MODE: ${{ vars.VITE_APP_DEV_MODE }}
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: 
        cd prototype && 
        docker build . --file "Dockerfile" --tag bachelor:latest 
        --build-arg MONGO_PASSWORD=${{ env.MONGO_PASSWORD }}
        --build-arg SECRET=${{ env.SECRET }}
        --build-arg CLIENT_APP_URL=${{ env.CLIENT_APP_URL }}
        --build-arg MONGO_DB=${{ env.MONGO_DB }}
        --build-arg MONGO_URL=${{ env.MONGO_URL }}
        --build-arg MONGO_USER=${{ env.MONGO_USER }}
        --build-arg SMTP_HOST=${{ env.SMTP_HOST }}
        --build-arg SMTP_PORT=${{ env.SMTP_PORT }}
        --build-arg SMTP_USER=${{ env.SMTP_USER }}
        --build-arg SMTP_PASS=${{ env.SMTP_PASS }}
        --build-arg VITE_API_URL=${{ env.VITE_API_URL }}
        --build-arg VITE_DEV_MODE=${{ env.VITE_APP_DEV_MODE }}
  deploy:
    needs: build
    runs-on: self-hosted
    environment: 
      name: production
    env:
      MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
      SECRET: ${{ secrets.SECRET }}
      CLIENT_APP_URL: ${{ vars.CLIENT_APP_URL }}
      MONGO_DB: ${{ vars.MONGO_DB }}
      MONGO_URL: ${{ vars.MONGO_URL }}
      MONGO_USER: ${{ vars.MONGO_USER }}
      SMTP_HOST: ${{ vars.SMTP_HOST }}
      SMTP_PORT: ${{ vars.SMTP_PORT }}
      SMTP_USER: ${{ vars.SMTP_USER }}
      SMTP_PASS: ${{ secrets.SMTP_PASS }}
    steps:
      - name: Deploy the newest Docker image
        run: docker compose -f "prototype/docker-compose.ci.yml" up -d
      - name: Delete all old and unused Images
        run: docker system prune -af